services:
  django:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: django
    restart: always
    ports:
      - '8000:8000'
    depends_on:
      - postgres
      - redis
    volumes:
      - ./src/:/usr/src
    networks:
      - django_network
      - nginx_network
    env_file:
      - ./.env

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - '5433:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - django_network
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - '5050:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - django_network
    depends_on:
      - postgres
    env_file:
      - ./.env

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
    networks:
      - django_network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    networks:
      - nginx_network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./src/staticfiles/:/usr/src/staticfiles
      - ./src/media/:/usr/src/media
      - ./src/logs/:/usr/src/logs
    depends_on:
      - django

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - django_network
    env_file:
      - ./.env
    command: redis-server --requirepass ${REDIS_PASSWORD:-12345678}
    volumes:
      - ./data/redis:/data

  celery:
    build:
      context: ./src
    container_name: celery_worker
    restart: always
    command: celery -A core worker -l info
    depends_on:
      - django
      - redis
    volumes:
      - ./src/:/usr/src
    networks:
      - django_network
    env_file:
      - ./.env

  celery_beat:
    build:
      context: ./src
    container_name: celery_beat
    restart: always
    command: celery -A core beat -l info
    depends_on:
      - redis
      - celery
    volumes:
      - ./src/:/usr/src
    networks:
      - django_network
    env_file:
      - ./.env

  flower:
    image: mher/flower
    container_name: flower
    restart: always
    ports:
      - '8888:8888'
    depends_on:
      - redis
      - celery
    networks:
      - django_network
    environment:
      - FLOWER_BROKER_URL=redis://:${REDIS_PASSWORD:-12345678}@redis:6379/0
      - FLOWER_PORT=8888
    env_file:
      - ./.env

volumes:
  postgres_data:
  redis_data:

networks:
  nginx_network:
  django_network:
